[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cython>=0.29.0",
    "numpy>=1.19.0",
    "pybind11>=2.6.0; implementation_name=='cpython'",
    "cmake>=3.12; implementation_name=='cpython'"
]
build-backend = "setuptools.build_meta"

[project]
name = "pyradar"
version = "0.1.0"
description = "A Python radar signal processing library with optional C++ acceleration"
authors = [
    { name = "Zhaoze Wang", email = "wangzhaoze@outlook.com" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.9"

dependencies = [
    "matplotlib",
    "numpy",
    "open3d",
    "pillow",
    "pre-commit",
    "pyparsing",
    "pyyaml",
    "scipy",
    "tabulate"
]

[project.urls]
"Homepage" = "https://github.com/Wangzhaoze/pyradar"
"Bug Tracker" = "https://github.com/Wangzhaoze/pyradar/issues"

[tool.setuptools]
package-dir = {"" = "."}  # 设置源代码就在当前目录

[tool.setuptools.packages.find]
where = ["."]


[tool.setuptools.package-data]
"pyradar" = ["*.so"]
