_target_: pyradar.base.Radar
# name: TI-MMWCAS-RF-EVM

waveform:
  _target_: pyradar.base.waveform.FMCW
  chirpSlope: 79000001052672.0
  startFrequency: 76999999488.0
  adcStartTime: 6.0e-06
  chirpIdleTime: 4.99999987369e-06
  rampEndTime: 3.99999998402e-5


sampler:
  _target_: pyradar.base.sampler.Sampler
  numChirpsPerFrame: 16
  numSamplesPerChirp: 256
  adcSampleRate: 8000000
  bitDepth: 16

transceivers:
  _target_: pyradar.base.transceivers.Transceivers
  TX: [
    [15, -34, 0],
      [19, -34, 0],
      [23, -34, 0],
      [24, -33, 0],
      [25, -30, 0],
      [26, -28, 0],
      [27, -34, 0],
      [31, -34, 0],
      [35, -34, 0],
      [39, -34, 0],
      [43, -34, 0],
      [47, -34, 0]
      ]
  RX: [
    [0, 0, 0],
      [1, 0, 0],
      [2, 0, 0],
      [3, 0, 0],
      [11, 0, 0],
      [12, 0, 0],
      [13, 0, 0],
      [14, 0, 0],
      [46, 0, 0],
      [47, 0, 0],
      [48, 0, 0],
      [49, 0, 0],
      [50, 0, 0],
      [51, 0, 0],
      [52, 0, 0],
      [53, 0, 0]
      ]
