_target_: pyradar.cfg.Radar
name: TI-MMWCAS-RF-EVM

waveform:
  _target_: pyradar.cfg.waveform.FMCW
  chirpDuration: 4.99999987369e-06
  chirpSlope: 7.90000010527e+13
  startFrequency: 76999999488.0

sampler:
  _target_: pyradar.cfg.sampler.Sampler
  numSamplesPerChirps: 256
  numChirpsperFrame: 16
  adcSampleRate: 8000000

transceivers:
  _target_: pyradar.cfg.transceivers.Transceivers
  numTX: 12
  numRX: 16
